### ISSUE TITLE
502 Bad Gateway - App accessible via IP from host machine

### ISSUE THREAD

**Issue by Jeewes** [progrium/dokku#1059]
I can access my application by running `curl 172.17.0.82:5000` on the host machine. Found that ip from:
```
# /home/dokku/app_name/nginx.conf

upstream app_name { server 172.17.0.82:5000; }
server {
  listen      [::]:80;
  listen      80;
  server_name app_name.mydomain.io ;
  location    / {
    proxy_pass  http://app_name;
    proxy_http_version 1.1;
    proxy_set_header Upgrade ;
    proxy_set_header Connection upgrade;
    proxy_set_header Host ;
    proxy_set_header X-Forwarded-Proto ;
    proxy_set_header X-Forwarded-For ;
    proxy_set_header X-Forwarded-Port ;
    proxy_set_header X-Request-Start ;
  }
  include /home/dokku/app_name/nginx.conf.d/*.conf;
}

# https://github.com/progrium/dokku/blob/master/docs/nginx.md#default-site
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name _;
  return 410;
  log_not_found off;
}
```
When I try to access the application with the `app_name.mydomain.io` I get __502 Bad Gateway__. Seems to me like Nginx does not "find" the application correctly. The domain did work initially, but after pushing another application (which I already removed) I got this problem..

Any ideas what should I do to help Nginx connect with the app correctly and avoid this in future?

__Additional information:__
I'm running Digital Oceans Dokku (3.1.5) pre-built image.

```
root@machine:~# docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED              STATUS              PORTS                     NAMES
99cf58f82f06        dokku/app_name:latest        "/start web"           About a minute ago   Up About a minute                             fervent_blackwell
49dd21e4cae1        postgresql/app_name:latest   "/usr/bin/start_pgsq   31 minutes ago       Up 31 minutes       0.0.0.0:49153->5432/tcp   jolly_torvalds

```

```
root@machine:/home/dokku/app_name# dokku logs app_name
Using rack adapter
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:5000, CTRL+C to stop
```

**Comment by josegonzalez** [comment]
What is the output of `nginx -t`?

**Comment by Jeewes** [comment]
Looks informative:
```
root@machine:/home/dokku/app_name# nginx -t
nginx: [emerg] invalid number of arguments in "proxy_set_header" directive in /home/dokku/app_name/nginx.conf:9
nginx: configuration file /etc/nginx/nginx.conf test failed
```

I'll try wihout the "proxy_set_header" statements.

**Comment by josegonzalez** [comment]
Is that a custom nginx conf file?

**Comment by Jeewes** [comment]
I followed [these instructions](https://github.com/progrium/dokku/blob/master/docs/nginx.md#customizing-the-nginx-configuration) and made a template file /home/dokku/app_name/nginx.conf.template by copying the original nging.conf file. I added the [default site snippet](https://github.com/progrium/dokku/blob/master/docs/nginx.md#default-site) to the end of template file.

After removing the "proxy_set_header" statements from _nginx.conf.template_ file and running `dokku ps:restart glinks` it seems to be working again. Which is good, but still don't understand what was the problem because those "proxy_set_header" statements were generated originally by Dokku.

**Comment by Jeewes** [comment]
The same 502 problem has occured again, but removing the nginx.conf.template and running `dokku ps:restart app_name` got it fixed. I think there is something fishy going on, but I can't pin point it for now. So I'll close this for now and reopen if I can provide more detailed issue.

Thanks for your help!

**Comment by fwolfst** [comment]
I experience similar issues when using (unmodified) the `nginx.ssl.conf.template`. Also the generated `nginx.conf` differs when I remove the template.

**Comment by Microserf** [comment]
I was bitten by this problem today, and I don't think it's related to dokku.

As per the instructions [here](https://hub.docker.com/r/library/nginx/) for interpolating environment variables into an nginx configuration file, the template is passed through the `envset` binary in order to substitute-in the appropriate variables.

`  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"`

The problem is that the `envsubst` command will also replace any/all `$variable` and `${variable}` tokens in the template, whether it is defined in the environment or not.

Therefore, if your configuration template contains a line like the following:

`        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

 ...it will be transformed into the following:

`        proxy_set_header X-Forwarded-For ;`


The solution I found was to limit the scope of the variables `envsubst` should interpolate, by listing them explicitly as the first argument:

`    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"`

Additionally, it's necessary to prefix each variable name with an additional dollar sign, so that docker-compose doesn't do the same thing envsubst does, which is to replace a variable's name with its empty/undefined value in the environment.

**Comment by josegonzalez** [comment]
@Microserf you're almost certainly using a (very) old version of Dokku. We no longer use bash for templating, and instead use [sigil](http://dokku.viewdocs.io/dokku/configuration/nginx/). Please update your installation to the latest version and refer to these docs for more information.

As well, we have never used a docker image for nginx, so that documentation doesn't apply here.

**Comment by Microserf** [comment]
@josegonzalez Sorry about the confusion. Let me clarify: I'm not a dokku user, but I had a similar issue, and this thread is one of the top results that came up in Google when I searched for the error I was seeing.

It looked like @Jeewes' initial issue description did involve Docker, so I thought the solution I found might be of interest to those in this thread, or those coming to this page from Google.

I don't know anything about dokku, so my apologies if this information is off-topic. :)
