### ISSUE TITLE
Why does Dokku wait for 35 seconds.

### ISSUE THREAD

**Issue by nahtnam** [progrium/dokku#1113]
Just wonder, why does dokku wait for 35 seconds?

**Comment by joshco** [comment]
Thats the default timer to make sure that your new container is up and running before sending traffic to it. Otherwise you can end up getting 5xx gateway errors while nginx sends traffic to an app that hasn't started accepting connections.

You can avoid this using the CHECKS zero downtime feature.
http://progrium.viewdocs.io/dokku/checks-examples.md

Create a CHECKS file with a shorter WAIT timer and set a URL check such as your app root.  Then dokku will just wait until it verifies that your app is accepting connections.

Make sure you have the latest version from the dokku repo.

**Comment by nahtnam** [comment]
Thanks for clarifying this!
