### ISSUE TITLE
Question: Waiting for 35 seconds ...

### ISSUE THREAD

**Issue by alexbeletsky** [progrium/dokku#1186]
I've stated new DO droplet with latest `dokku` on board, `v0.3.17` and redeployed the application I deployed on `dokku` many times before.

All is fine, expect one thing:

```
-----> Deploying socialsearch.io...
-----> Running pre-flight checks
       CHECKS file not found in container: running simple container check...
-----> Waiting for 35 seconds ...
-----> Default container check successful!
```

Now I have 35 seconds delay for each deployment. I have a static `nginx` based application there which doesn't require any special checks. Previously, I also had `Running pre-flight checks` (even if never used that) but it didn't cause any delays.

Is that possible to disable (re-configure) that somehow?

**Comment by 3onyc** [comment]
To completely disable it remove `/var/lib/dokku/plugins/checks`

Alternatively, the 35 seconds is `DOKKU_CHECKS_WAIT` and `DOKKU_CHECKS_TIMEOUT` combined, so reducing those through `dokku config:set` reduces the wait time.

**Comment by alexbeletsky** [comment]
Can you please explain me a logic behind "if I don't have CHECKS file, deployment waits for 35 secs". What it expected to happen during that 35 seconds, why this delay is introduced in a first place?

**Comment by 3onyc** [comment]
I think the reasoning behind that was to give new containers enough time to spin up, as for why the delay is 35 seconds, you'll have to ask someone else.

**Comment by kenips** [comment]
@alexbeletsky the pre-flight check is designed to detect if the (web) application has started up successfully, and, if so, proceed to finish the deploy and switch traffic from old to new container. This enables zero downtime deployments.

The 35 seconds is a default and should be placed by a CHECK file that actually check for signals indicating your app has booted up successfully.

See https://github.com/progrium/dokku/blob/1a151ddabe5377cf40cc25074a557763612afd32/docs/checks-examples.md for details.

**Comment by alexbeletsky** [comment]
@kenips thanks for details! 

My confusion caused by the fact, that in earlier dokku versions, I have something like that

```
-----> Running pre-flight checks
       check-deploy: /home/dokku/api/CHECKS not found. attempting to retrieve it from container ...
       CHECKS file not found in container. skipping checks.
```

Means, no `CHECKS` file - you do nothing. Now, I still don't have them (cause I'm not that interested in zero-time deployment scenarios) - but all my deployments are delayed for 35 seconds.

That logic doesn't seem right to me.

**Comment by kenips** [comment]
That's interesting as I was really existed about zero-downtime baked in. I guess the default is the choice of the author, but should align in what most people need. Whether zero-downtime is a niche or majority that I do not know.

Heroku implements it as a feature that needs to be turned on explicitly. I guess dokku could implement something similar?

**Comment by josegonzalez** [comment]
@alexbeletsky this is a better default for the majority of our users. People would deploy and then have a broken app, wondering why "dokku" broke their deploys (when in reality it was that their command failed to start successfully and crashed the container). In order to head off the number of issues pouring in, we decided to implement container checking as the default check.

If you would rather not do this, I would suggest making a PR to dokku to disable the feature based on a config value - `DOKKU_ZERO_DOWNTIME=false` or something. You would then be able to set this in the global env file or on a per-app basis.

**Comment by alexbeletsky** [comment]
@josegonzalez motivation is understood, thank you.

I'm totally fine with zero-based deployment concept, but still do not understand the logic here.

If I didn't add any `CHECK` file, that would mean that I'm not interested in pre-flight checks, I'm explicitly saying - I don't need it. In my case it makes sense, since lately I use dokku a lot for serving static sites based on [heroku-buildpack-nginx](https://github.com/alexbeletsky/heroku-buildpack-nginx), which almost "guaranteed" to start ok.

Now, go back to the case. Currently, the deployment is delayed for 35 secs, but what is the reason for it? If an application in a new container is broken, it will be deployed after 35 seconds, since there are no checks performed. It seems like a waste of time, nothing more.

It looks like I'm missing something and really appreciate the clarification.

**Comment by michaelshobbs** [comment]
That assumption is not necessarily true. In the default plugin set (i.e. no supervisor plugin and only a web proc) if startup fails, the container will exit. I agree that the container could fail after the default 35 second timeout, or not at all in the case of an nginx buildpack deploy, and that's why you can either add a CHECKS file for more efficient checking or set `DOKKU_CHECKS_TIMEOUT`to `0`. 35 seconds was chosen as a pragmatic *default* and is meant to be tuned by you, the user, if you deem it necessary.

I also concur with @josegonzalez that adding a way to disable the entire checks plugin is a nice lever to add.

As a side note, I wonder how prominent nginx buildpack deploys are in the wild. Most feedback that comes in via issues and IRC are things like node, python, ruby and maybe java?

**Comment by joshco** [comment]
Are you using the latest version?  You should see
````
"For more efficient zero downtime deployments, create a file CHECKS."
"See http://progrium.viewdocs.io/dokku/checks-examples.md for examples"
"CHECKS file not found in container: Running simple container check..."
````
from: https://github.com/progrium/dokku/blob/master/plugins/checks/check-deploy#L80-L83

**Comment by alexbeletsky** [comment]
Applied @3onyc suggestion, by chaning `DOKKU_CHECKS_WAIT` and `DOKKU_CHECKS_TIMEOUT` env. variables.
