### ISSUE TITLE
DOCKERFILE_ENV_FILE file starting appearing...

### ISSUE THREAD

**Issue by vincentfretin** [progrium/dokku#1188]
With dokku master, I have a DOCKERFILE_ENV_FILE file in my app when I repush my app.
If I do ps:rebuild myapp, I don't have it.

The file is created from plugins/config/docker-args-deploy
To my understanding, this file should be only created if the app is not buildstep based.
I think there is an issue here, maybe $IMAGE is empty in the case of a git push deploy master?

**Comment by vincentfretin** [comment]
Hi @michaelshobbs you wrote this code, is this a bug or a feature? :)

**Comment by michaelshobbs** [comment]
Probably a bug. :smiley: I'll take a look.

**Comment by michaelshobbs** [comment]
A cursory run of `ps:rebuild` didn't yield the behavior you described. However, if somehow there was no `dokku/$APP` image then we would attempt to create this file and the `docker run` command to inspect the image would fail. Not sure what the expected behavior of `is_image_buildstep_based` should be if the image is not found. Perhaps exit with a different status?

**Comment by vincentfretin** [comment]
I can't reproduce it now, weird. I updated dokku yesterday, maybe there was a fix in it, I don't know. I close the issue.

**Comment by Benjamin-Dobell** [comment]
I just ran into this as well. Ran:

    sudo apt-get update
    sudo apt-get upgrade
    sudo dokku ps:rebuild <app>

Now, I'm not sure if the file appeared then. It may have appeared after a reboot, then another:

    sudo dokku ps:rebuild <app>

Which did actually fail due to a Docker issue https://github.com/docker/docker/issues/9665

I then ran:

    sudo service docker restart
    sudo dokku ps:rebuildall

It was only at this point that I noticed that ```/home/dokku/<app>/DOCKERFILE_ENV_FILE``` existed - I did not check any earlier.

It's worth noting that ````DOCKERFILE_ENV_FILE```` does only exist for one specific <app>; the one I was rebuilding on its lonesome and failed at one point. I have many other apps and that were rebuilt with the ps:rebuildall, but they do not have this file.

**Comment by Benjamin-Dobell** [comment]
By the way, here is the output of when I encountered the Docker aufs bug:

```
-----> Deploying ar-sandbox...
time="2015-07-30T13:28:20+10:00" level=fatal msg="Error response from daemon: Cannot destroy container 6b397e328cf1948f644b3b28fa98b6bec4cd282e214d507e3c050617547a4886: Driver aufs failed to remove root filesystem 6b397e328cf1948f644b3b28fa98b6bec4cd282e214d507e3c050617547a4886: rename /var/lib/docker/aufs/mnt/6b397e328cf1948f644b3b28fa98b6bec4cd282e214d507e3c050617547a4886 /var/lib/docker/aufs/mnt/6b397e328cf1948f644b3b28fa98b6bec4cd282e214d507e3c050617547a4886-removing: device or resource busy" 
time="2015-07-30T13:28:21+10:00" level=fatal msg="Error response from daemon: Cannot destroy container c8d003d422c5a583ee048ed3875d0ab9625acb354a6b42e7e1f617fc20d27275: Driver aufs failed to remove root filesystem c8d003d422c5a583ee048ed3875d0ab9625acb354a6b42e7e1f617fc20d27275: rename /var/lib/docker/aufs/mnt/c8d003d422c5a583ee048ed3875d0ab9625acb354a6b42e7e1f617fc20d27275 /var/lib/docker/aufs/mnt/c8d003d422c5a583ee048ed3875d0ab9625acb354a6b42e7e1f617fc20d27275-removing: device or resource busy" 
-----> Running pre-flight checks
App container failed to start!!
/usr/local/bin/dokku: line 49: 16963 Killed                  dokku deploy "$APP"
```

My guess is that the AUFS bug was encountered by Docker, but Dokku didn't abort immediately. Presumably Dokku was expected to change to a directory (but failed) so the ```DOCKERFILE_ENV_FILE``` file was created in the wrong directory... feasible?
