### ISSUE TITLE
Container restarting

### ISSUE THREAD

**Issue by yngndrw** [progrium/dokku#1191]
Should containers have the following Docker run option by default ?
```bash
--restart=always
```

**Comment by josegonzalez** [comment]
Why?

**Comment by yngndrw** [comment]
So that the containers continue to run until Dokku (Or you) explicitly wants it to stop. Obviously this won't affect the processes running inside the container, but I think it's a reasonable expectation to expect the container to keep running until you push up a new build or stop it.

**Comment by vincentfretin** [comment]
You don't want this option. For several reasons, first it conflicts with the upstart script that restart the applications when docker daemon start. Secondly, if the container restart automatically because of a failure of your process, it will have a different ip, and the nginx.conf will not be updated with the new ip.

**Comment by michaelshobbs** [comment]
:+1: to what @vincentfretin said

**Comment by josegonzalez** [comment]
I'd agree with @vincentfretin. If you need your process to stay alive regardless of application failure, you should use a process manager inside of the docker container.
