### ISSUE TITLE
Is it easy to migrate out of Dokku to Deis?

### ISSUE THREAD

**Issue by windweller** [progrium/dokku#1234]
Hi! I know Dokku is sponsored by Deis and I found this website: http://deis.io/deis-sponsors-dokku/. It seems like they mention that there will be an official "migration" guide from Dokku to Deis. I'm helping a start-up company that focuses on building quick-iteration outburst type "viral" apps (they get a lot of users very quickly and then slowly disappear). So scaling up and down easily becomes a concern. I've never used Deis (but have enough experience with Dokku). Is it easy to migrate from Dokku to Deis? Can I start with Dokku?

The server stack is going to be on AWS, and I'm thinking of using load balancing when traffic becomes big.

The reason I don't understand Deis is that I don't know how one command can scale up server (somehow register/provision and start a new machine?).

**Comment by michaelshobbs** [comment]
@progrium thoughts here?

**Comment by progrium** [comment]
Your apps will be compatible, but the workflow is just slightly different since you'd use the Deis command line tool much more like Heroku. There are certain features in Dokku enabled by plugins that may not work in Deis but may have an equivalent. An actual guide is not a bad idea. I think even if it was implied, it was not on our list of deliverable, so I'll look into that.

Also, about provisioning/scaling ... Deis has provisioning tools but its system is primarily designed to run on a cluster already provisioned. It can add nodes, but I don't believe it supports "burstiness" with new hosts, but instead deploying more instance of your app to other hosts in your cluster.

**Comment by windweller** [comment]
@progrium Thank you for answering, that helps :) I guess I've just been confused by the whole relationship between Deis, Dokku, (and even Flynn). It seems to me that Flynn is easier to learn or use than Deis (it also doesn't have restriction on number of servers to start with). Do you know the current status of Flynn (most articles/videos are old and are not detailed)? 

I'm not a system engineer, just a software engineer (aka bash scripting, provisioning, system configuration are not my forte). I'm trying to avoid mistakes by using automation tools like Dokku or Deis, but I want to do it right. This might be slightly off the topic, but do you think about-to-grow-up Start-ups should hire a system engineer or just use consulting service?

**Comment by progrium** [comment]
I don't know current state of Flynn but I'm glad to hear it's easier to learn. I think that's changed quite a bit. You may have also heard about Empire today. 

Things are changing so much right now and there's lots of unknowns and gotchas. Glider Labs provides consulting where we help you build a PaaS-like delivery pipeline and automation tools that's quite a bit simpler than Flynn and Deis, and more customized to your needs. So I'm biased, I would say use a consulting service and specifically Glider Labs.
