### ISSUE TITLE
How does Dokku translate Procfile to Dockerfile?

### ISSUE THREAD

**Issue by windweller** [progrium/dokku#1325]
Hi! I know this could be a lot to ask. I've been using Dokku for one and a half year, and I'm moving to a more pure Docker approach. However, I really want to write a Dockerfile for my image that is similar to Dokku's build process. I'm using Golang and I can notice that Dokku uses godep to build my program each time. Where can I find the interpretation engine that Dokku uses to translate Procfile to Dockerfile?

**Comment by michaelshobbs** [comment]
I'm not sure what you are asking. Dokku doesn't translate Procfiles into Dockerfiles. However, I'll take a stab at clarifying and see what questions remain.

- dokku's dockerfile deployment just does a `docker build -t` and a `docker run` on that built image.
- dokku's Heroku-style deployment builds a docker image starting with (currently) [buildstep](https://github.com/progrium/buildstep). we then run the `builder` process that executes the correct Heroku buildpack. then the Procfile is parsed and executed in a container executed from that built docker image. I skipped some steps for brevity and because any number of plugins can modify this process substantially.

**Comment by windweller** [comment]
I see! I was migrating my Dokku project to a more Docker-based project, with Dockerfile. I want to write similar building steps that Dokku uses into my Dockerfile and I was afraid I might get it wrong. I guess I should just go and find Heroku buildpack for Golang and use that. Thank you for pointing me to buildstep.
