### ISSUE TITLE
! [remote rejected] master -> master (pre-receive hook declined)

### ISSUE THREAD

**Issue by philipheinser** [progrium/dokku#1329]
https://gist.github.com/Sommerfeld/322332b176143fec82c9

**Comment by michaelshobbs** [comment]
This is an error installing your node modules it would seem. Maybe try installing them fresh locally and debug from there?

**Comment by philipheinser** [comment]
locally nam install runs fine.

**Comment by philipheinser** [comment]
A test server with just 

```
var express = require('express')

var app = express()

app.listen(process.env.PORT)
```

also fails.

https://gist.github.com/Sommerfeld/949505521d9590d88fe5

**Comment by michaelshobbs** [comment]
This is a different error than the one you specified originally. 

If it were me, I'd look further into the npm install issue of the first error. 

The second error is due to you not having a Procfile and not having the correct section in package.json to tell the build pack how to start your server. 

Point being this is either an app or buildpack issue.
