### ISSUE TITLE
Makefile is using old version of plugn, leaves remnants in /tmp

### ISSUE THREAD

**Issue by u2mejc** [progrium/dokku#1479]
I was reviewing the sweet new CONTRIBUTING.md and it calls for an issue to be created before PR. (Maybe small changes don't need a issue since we can talk in PRs too?)

Once @progrium tags the new plugn release, I'll rebase and shoot the PR over.

Ref: https://github.com/progrium/plugn/issues/6

**Comment by josegonzalez** [comment]
I believe the debian package we install is the proper version - I built from source - so thankfully this only affects manual installations.

**Comment by josegonzalez** [comment]
Since we can't seem to get a hold of @progrium, I've moved the `plugn` binary reference to the `0.4.0` release of dokku on github. 

For reference, I pulled the `plugn` binary installed on my dokku installation, which was verified as the same as that which is in the 0.2.0 debian package. I also added the debian package to our 0.4.0 release.

Waiting on tests to pass before merging.
