### ISSUE TITLE
Per App Permissions

### ISSUE THREAD

**Issue by wzrdtales** [progrium/dokku#1532]
I have not found a plugin for this yet, if this already exist **please** let me now, maybe I'm also going to look to implement it myself. For now just leaving my thoughts here.

It would be great to have permissions to a single application instead of a whole server. Maybe this can be done as a per user config. Supporting groups wouldn't be necessary and just be a convience feature instead.

**Comment by michaelshobbs** [comment]
I'm not aware of a plugin that does this either but sounds like a good idea.

**Comment by mlebkowski** [comment]
@wzrdtales, are you looking for something like https://github.com/mlebkowski/dokku-acl?

**Comment by josegonzalez** [comment]
@mlebkowski would be nice if your readme had an example workflow. Atm it's a bunch of text I can't decipher. To be fair, I'm quite inebriated, but still.

One thing that doesn't allow for is per-app plugin manipulation. Kind of difficult to do since it's not like we have any place to hook into at the moment.

**Comment by u2mejc** [comment]
@mlebkowski's plugin looks mature today and appears to meet @wzrdtales request. Ok to close?

**Comment by josegonzalez** [comment]
That and the hook in #1671 should allow developers to write whatever advanced hooks they would like to. I'm of the opinion that this belongs in a community plugin, not dokku core, so closing.
