### ISSUE TITLE
New log prefix breaks JSON format for bunyan

### ISSUE THREAD

**Issue by xadh00m** [progrium/dokku#1534]
Hi,

while the new log line prefix improves general monitoring capabilities it breaks the log format. Some of our services support logging as JSON for *bunyan*. So that we could use it as follows:

```
ssh dokku@<host> logs <app> -t | bunyan
```
Is there a way to get the raw logs instead? Would it be possible to disable/omit the prefix with an explicit call?

Thanks,
Mirko

**Comment by josegonzalez** [comment]
Yes, thats definitely possible. There are a few things we can do here:

- Allow specifying a specific process to tail logs for. Something like `--ps web` might be good. Might also be worth adding support for multiple processes by comma-separating them, though heroku does not provide this.
- We should have a `--no-prefix` flag - or similar - to handle this specific request.
- Logs should use the word `app` instead of the app name I think, if we're going to follow what heroku does. Example [here](https://devcenter.heroku.com/articles/logging#view-logs)
- It's unclear to me whether we should add in nginx logs to the output of `dokku logs` for a specific service. My gut says yes, and have the source be `dokku[nginx]`. If we implement this, we should also add a `--source nginx|app` flag, so that we can filter out logs based on what is outputting them.
  - This *might* be broken if a user does not use nginx for their router - perhaps if they replace it with something like dokku-haproxy - but that's yet unclear to me. We may want to keep track of what logfiles to tail somewhere for an app somehow.

@Flink @michaelshobbs thoughts?

**Comment by Flink** [comment]
@josegonzalez seems good to me :)

**Comment by michaelshobbs** [comment]
I don't have a current mental model of the log plugin at the moment but here goes.

1. sounds good
2. `--no-prefix` feels too verbose. maybe `-q or --quiet`
3. we'll still need to use the app name i.e. `dokku logs <app_name>....` as we don't have the app context necessarily. i think this needs to be flesh out more
4. if we go with 1 then, we don't need `--source` (something like `dokku logs node-js-app --ps web|worker|app`;with app being all proc types perhaps?) 

also i'd say let the nginx plugin handle logs as it does now. that way the haproxy plugin can implement it's own log exposure as well.

**Comment by Flink** [comment]
So maybe what we want in the end is a `logs` plugin entirely mimicking the one from Heroku ;)

**Comment by michaelshobbs** [comment]
While this is great in principle, our implementation varies in that the user must explicitly tell us with which app they want to interact. So, we can't mimic the UI entirely.

**Comment by Flink** [comment]
yes but we can mimic all the rest :)

**Comment by josegonzalez** [comment]
Meant to assign @Flink, but I can't since I'm not repo owner. @progrium, mind adding Flink to this repo as a contributor?

@Flink since you worked on the most recent logging changes, mind taking a stab at this when you get a chance?

**Comment by Flink** [comment]
@josegonzalez no problem, I’ll take a look!
