### ISSUE TITLE
Running multiple services from a Dockerfile project

### ISSUE THREAD

**Issue by wjdp** [progrium/dokku#1594]
I'm looking at http://progrium.viewdocs.io/dokku/process-management/ and trying to work out how to get several services running from a single project.

I have a repo with a Dockerfile:

```
FROM wjdp/flatcar

ADD . app

RUN /app/bin/install.sh

EXPOSE 8000

CMD /app/bin/run.sh
```

run.sh starts up a single threaded web server. This works fine but I'd like to run several services.

I tried making a Procfile with a single line of web: /app/bin/run.sh
and removing the CMD line from the Dockerfile. This doesn't work as without a command to run the Docker container doesn't stay alive and dokku gets sad:

```
remote: Error response from daemon: Cannot kill container ae9d50af17deed4b50bc8327e53ee942bbb3080d3021c49c6604b76b25bb898e: Container ae9d50af17deed4b50bc8327e53ee942bbb3080d3021c49c6604b76b25bb898e is not running
remote: Error: failed to kill containers: [ae9d50af17deed4b50bc8327e53ee942bbb3080d3021c49c6604b76b25bb898e]
```

**Comment by wjdp** [comment]
I've just been reading up on fig/docker-compose and the https://github.com/project-nsmg/figure project. Seems a lot of the building blocks are about, is support for compose present / coming soon?

**Comment by josegonzalez** [comment]
I reached out to the developer of figure [here](https://github.com/project-nsmg/figure/issues/3) asking if he would mind making PRs. Unfortunately the first push was essentially "rename dokku everywhere" so it would be difficult to even diff from the time it was forked. We've since changed our codebase quite a bit, so at this point merging it in would be quite a pain.

[Here](https://github.com/progrium/dokku/tree/docker-compose-support) is a branch where I experimented with docker-compose support. The hard part atm is figuring out what each process is and emulating that in the same way we do Procfiles...

As far as running several services via Dockerfile... we actually don't have a great story in dokku yet. #1564 is a related issue, but we haven't done anything to work towards a solution. You could run a process manager inside your dockerfile?

**Comment by josegonzalez** [comment]
If you'd like to help spec out either docker-compose support or better Dockerfile support, that would be stellar. Let me check on what the docker-compose support branch does now...

**Comment by josegonzalez** [comment]
Note, we don't have a good solution for this at the moment, and rather than have the conversation in two places, I'm closing so that we can have it all in #1564.
