### ISSUE TITLE
Problem access database postgresql  with ruby in dokku

### ISSUE THREAD

**Issue by fabdelgado** [progrium/dokku#1733]
Hi I have an application on rails and want to access from external ruby script in the application using the same database.

Try follows but results

/var/lib/gems/1.9.1/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:241:in `initialize': PG::ConnectionBad: FATAL:  password authentication failed for user "postgres" (Sequel::DatabaseConnectionError)
FATAL:  password authentication failed for user "postgres"

My code in ruby is:
#Connection to database
conn = Sequel.postgres('tilo_cms', :user=>'postgres',
       :password=>'ff76e153f06737d69e7036cc96a944fe', :host=>'localhost', :port=>5432,
       :max_connections=>10)

**Comment by josegonzalez** [comment]
This isn't an issue with dokku - dokku does not come out of the box with postgres - but rather an issue with your application code. If you have an issue with a specific plugin, please re-file at that plugin's issue tracker.

Note: It seems like your host is invalid, since postgres wouldn't be running inside of your container, but rather potentially inside of another one.
