### ISSUE TITLE
496 & 497 NOT working for pre-receive hook declined

### ISSUE THREAD

**Issue by dskvr** [progrium/dokku#649]
I used the following code, sometime last month, which fixed this issue 

    sudo wget -O /etc/init/docker.conf https://raw.github.com/dotcloud/docker/master/contrib/init/upstart/docker.conf
    sudo service docker restart

But only temporarily. I tried to push again (4 weeks later) and I got the nasty error again.

     ! [remote rejected] master -> master (pre-receive hook declined)

This bug is like kryptonite to my patience. It appears that all issues for this happening in Dokku lead back to issues #496 & #497, and I have applied fixes in these issues without relief. I am running Nginx on DigitalOcean using *Dokku v0.2.3 on Ubuntu 14.04 (w/ Docker 1.0)*

Any tips?

**Comment by michaelshobbs** [comment]
More DO oddness? Does our recent documentation addition cover this well enough?

**Comment by josegonzalez** [comment]
Add a note about the resolvconf I guess and we can close this.

**Comment by dewstend** [comment]
Installing Dokku (and therefore Docker) in fresh installations of Ubuntu 18.04 will bring a non-configured Docker that isn't able to connect to the internet, and silently fails.

**Comment by 0atman** [comment]
@dewstend would you make a new issue please?

**Comment by josegonzalez** [comment]
Note: if installing docker results in not being able to run containers that can talk to the internet, that sounds like a docker bug. We call their installer script from ours, so that seems like a bug on their end.

That said, without further information, it's hard to say what happened. Please don't comment on 6 year old issues and file a new ticket instead.
