### ISSUE TITLE
Problems on deploy (nodejs.org not reliable?)

### ISSUE THREAD

**Issue by AlbertoValenzuela** [progrium/dokku#953]
Hi. I have a little problem when I will deploy a rails app. After installing a gem and trying to deploy, I get this error:

> Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 30 --max-time 30 http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz -s -o - | tar zxf - node-v0.10.30-linux-x64/bin/node' failed unexpectedly:

I think it has to do with [this issue](https://github.com/heroku/heroku-buildpack-ruby/pull/336) which is [fixed here](https://github.com/heroku/heroku-buildpack-ruby/commit/0714d7e2eb0091de7b0af8d632343386854d94d2). But I have no idea how to fix it by myself. Or even if I can.

I just updated the buildsteps, but it ins't fixing the problem.

**Comment by michaelshobbs** [comment]
You can include a `.env` file in the root of your repo and `export BUILDPACK_URL` as the github url to the latest buildpack. 

If that doesn't solve it and you are using Digital Ocean; we've seen issues using IPv6 and sometimes rebooting with sort out DO network oddities.

**Comment by AlbertoValenzuela** [comment]
Thanks for your answer @michaelshobbs. I finally installed [@pauldub's multi-buildpack plugin](https://github.com/pauldub/dokku-multi-buildpack) for dokku and it worked fine at the next push. **I don't even needed** to do something like `config:add BUILDPACK`. Which seems a bit crazy. :camel: 

Should this be fixed by dokku itself or it is something someone should fix by himself? From what I read at the mentioned issue on heroku's repository it's a almost new problem.

**Comment by michaelshobbs** [comment]
Glad that got your issue sorted out. You are correct. It is a new change. I think they got tired of hearing about nodejs.org instability. :smile:

I'm sure it will be updated in the next (buildstep)[https://github.com/progrium/buildstep]. The `buildstep` image contains (most) buildpacks at the time the image was created. This is done primarily for convenience. 

Since we always have the option to set a BUILDPACK_URL, it seems buildpack bugs in the "packaged" buildpack set are generally treated as lower priority. 

You might want to open an issue against the buildstep project. Generally, I've seen it necessary for some level of issue count "critical-mass" to build up before a new buildstep release is created.

**Comment by dyson** [comment]
PR and further info can be found at https://github.com/progrium/buildstep/issues/132
